version: '3.8'
services:
  web:
    container_name: tanvoid0-api
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*